import './styles/main.postcss'
// import routes generated by Pages
import routes from 'vite-plugin-pages/client'
// progress bar
import NProgress from 'nprogress'
import { ViteSSG } from 'vite-ssg'
import installPlugins from './plugins'
import App from './App.vue'

// Vite Server Side Generation
export const createApp = ViteSSG(
  App,
  { routes },
  ({ app, router, isClient }) => {
    installPlugins(app)
    // Use NProgress in vue router
    if (isClient) {
      router.beforeEach(() => { NProgress.start() })
      router.afterEach(() => { NProgress.done() })
    }
  },
)
